name: feature

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Prepare Dependencies
        working-directory: web
        run: yarn install
      - name: Lint
        working-directory: web
        run: yarn lint
  lint-cms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Prepare Dependencies
        working-directory: cms
        run: yarn install
      - name: Lint
        working-directory: cms
        run: yarn lint
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Prepare Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            web/.cache/
            web/public/
            web/node_modules/
          key: ${{ runner.os }}-web-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-web-
      - name: Add Firebase Admin Secret
        working-directory: web
        run: echo ${{ secrets.FIREBASE_ADMIN_CREDENTIALS }} > credentials.json
      - name: Prepare Dependencies
        working-directory: web
        run: yarn install
      - name: Build
        working-directory: web
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: web/public
      - name: get-env-name
        id: get-env
        uses: actions/github-script@v5
        with:
          script: |
            const branch = context.ref.replace('refs/heads/','')
            core.setOutput('env_name',branch)
    outputs:
      env_name: ${{ steps.get-env.outputs.env_name }}
  build-cms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Prepare Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            cms/.cache/
            cms/build/
            cms/node_modules/
          key: ${{ runner.os }}-cms-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cms-
      - name: Prepare Dependencies
        working-directory: cms
        run: yarn install
      - name: Build
        working-directory: cms
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cms
          path: cms/build
  deploy-feature:
    runs-on: ubuntu-latest
    needs:
      - build-web
      - build-cms
    environment:
      name: ${{ needs.build-web.outputs.env_name }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Web Artifact
        uses: actions/download-artifact@v2
        with:
          name: web
          path: web/public
      - name: Download CMS Artifact
        uses: actions/download-artifact@v2
        with:
          name: cms
          path: cms/build
      - name: Deploy Feature
        id: deploy
        uses: joinflux/firebase-action@master
        with:
          args: hosting:channel:deploy ${{ needs.build-web.outputs.env_name }} | tee output.txt && echo \"::set-output name=url::$(grep 'Channel URL' output.txt | grep -o 'https://[^ ]*')\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
