name: feature

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
  GHOST_CONTENT_API_KEY: ${{ secrets.GHOST_CONTENT_API_KEY }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with: 
          node-version: 14.x
      - name: Prepare Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with: 
          node-version: 14.x
      - name: Prepare Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            .cache/
            public/
            node_modules/
          key: ${{ runner.os }}-build-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Prepare Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
  deploy-feature:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.ref }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Package
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - name: Deploy Feature
        id: deploy
        uses: joinflux/firebase-action@master
        with:
          args: hosting:channel:deploy ${{ github.ref }} | tee output.txt && echo \"::set-output name=url::$(grep output.txt -o \'https://[^ ]*\')\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Comment on PR
        if: github.event_name	== 'pull_request'
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Build Complete - Temporary Environment can be viewed at this URL: ${{ steps.deploy.outputs.url }}'
            })
  