name: main

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Prepare Dependencies
        working-directory: web
        run: yarn install
      - name: Lint
        working-directory: web
        run: yarn lint
  lint-cms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Prepare Dependencies
        working-directory: cms
        run: yarn install
      - name: Lint
        working-directory: cms
        run: yarn lint
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Prepare Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            web/.cache/
            web/public/
            web/node_modules/
          key: ${{ runner.os }}-web-${{ hashFiles('web/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-web-
      - name: Prepare Dependencies
        working-directory: web
        run: yarn install
      - name: Build
        working-directory: web
        env:
          FIREBASE_ADMIN_CREDENTIALS: ${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: web/public
  build-cms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Prepare Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            cms/.cache/
            cms/build/
            cms/node_modules/
          key: ${{ runner.os }}-cms-${{ hashFiles('cms/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cms-
      - name: Prepare Dependencies
        working-directory: cms
        run: yarn install
      - name: Build
        working-directory: cms
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cms
          path: cms/build
  deploy-union:
    runs-on: ubuntu-latest
    needs:
      - build-web
      - build-cms
    environment:
      name: union
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Web Artifact
        uses: actions/download-artifact@v2
        with:
          name: web
          path: web/public
      - name: Download CMS Artifact
        uses: actions/download-artifact@v2
        with:
          name: cms
          path: cms/build
      - name: Deploy
        id: deploy
        uses: joinflux/firebase-action@master
        with:
          args: hosting:channel:deploy --expires 30d union | tee output.txt && echo \"::set-output name=url::$(grep 'Channel URL' output.txt | grep -o 'https://[^ ]*')\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-union
    environment:
      name: stage
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Web Artifact
        uses: actions/download-artifact@v2
        with:
          name: web
          path: web/public
      - name: Download CMS Artifact
        uses: actions/download-artifact@v2
        with:
          name: cms
          path: cms/build
      - name: Deploy
        uses: joinflux/firebase-action@master
        with:
          args: hosting:channel:deploy --expires 30d stage | tee output.txt && echo \"::set-output name=url::$(grep 'Channel URL' output.txt | grep -o 'https://[^ ]*')\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-stage
    environment:
      name: production
      url: https://startupresource.center
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Web Artifact
        uses: actions/download-artifact@v2
        with:
          name: web
          path: web/public
      - name: Download CMS Artifact
        uses: actions/download-artifact@v2
        with:
          name: cms
          path: cms/build
      - name: Deploy
        uses: joinflux/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
